# Generated by Django 5.0 on 2024-01-02 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('calorie_density', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=10000)),
                ('picture', models.BinaryField(blank=True, null=True)),
                ('description', models.CharField(max_length=150)),
                ('is_boosted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('category_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('has_mod_rights', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('picture', models.BinaryField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('unban_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DishDiscoverDjango.ingredients')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DishDiscoverDjango.recipes')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1000)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DishDiscoverDjango.recipes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DishDiscoverDjango.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('is_predefined', models.BooleanField()),
                ('tag_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DishDiscoverDjango.tagcategory')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DishDiscoverDjango.recipes')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DishDiscoverDjango.tags')),
            ],
        ),
        migrations.AddField(
            model_name='ingredients',
            name='tag_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DishDiscoverDjango.tags'),
        ),
        migrations.CreateModel(
            name='SavedRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recommendation', models.BooleanField()),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DishDiscoverDjango.recipes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DishDiscoverDjango.user')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTickets',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=150)),
                ('comment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DishDiscoverDjango.comments')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DishDiscoverDjango.recipes')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_tickets', to='DishDiscoverDjango.user')),
                ('violator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_tickets', to='DishDiscoverDjango.user')),
            ],
        ),
        migrations.AddField(
            model_name='recipes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DishDiscoverDjango.user'),
        ),
        migrations.CreateModel(
            name='LikedRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recommendation', models.BooleanField()),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DishDiscoverDjango.recipes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DishDiscoverDjango.user')),
            ],
        ),
        migrations.CreateModel(
            name='PreferredTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DishDiscoverDjango.tagcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DishDiscoverDjango.user')),
            ],
            options={
                'unique_together': {('user', 'tag')},
            },
        ),
    ]
