# Generated by Django 5.0 on 2024-01-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DishDiscoverDjango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='recipes',
            field=models.ManyToManyField(through='DishDiscoverDjango.RecipeIngredient', to='DishDiscoverDjango.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='DishDiscoverDjango.RecipeIngredient', to='DishDiscoverDjango.ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(through='DishDiscoverDjango.RecipeTag', to='DishDiscoverDjango.tag'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_tags',
            field=models.ManyToManyField(through='DishDiscoverDjango.PreferredTag', to='DishDiscoverDjango.tag'),
        ),
    ]
