# Generated by Django 5.0 on 2024-01-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DishDiscoverDjango', '0002_alter_dishdiscoveruser_preferred_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
