# Generated by Django 5.0 on 2024-01-12 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DishDiscoverDjango', '0002_ingredient_recipes_recipe_ingredients_recipe_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recipes',
        ),
    ]
