# Generated by Django 5.0 on 2024-01-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DishDiscoverDjango', '0003_alter_recipe_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(max_length=3000),
        ),
    ]
