# Generated by Django 5.0 on 2024-01-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DishDiscoverDjango', '0003_alter_recipe_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='calorie_density',
            field=models.FloatField(null=True),
        ),
    ]
