# Generated by Django 5.0 on 2024-01-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DishDiscoverDjango', '0004_alter_ingredient_calorie_density'),
        ('DishDiscoverDjango', '0004_alter_recipe_description'),
    ]

    operations = [
    ]
