# Generated by Django 5.0.1 on 2024-01-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishdiscoveruser',
            name='liked_recipes',
            field=models.ManyToManyField(related_name='users_liked_recipes', through='recipes.LikedRecipe', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='dishdiscoveruser',
            name='saved_recipes',
            field=models.ManyToManyField(related_name='users_saved_recipes', through='recipes.SavedRecipe', to='recipes.recipe'),
        ),
    ]
