# Generated by Django 5.0 on 2024-01-29 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_dishdiscoveruser_picture_alter_recipe_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportticket',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
    ]
